# Generated by Django 5.2.6 on 2025-10-30 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadias', '0003_estadia_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Pix'), ('2', 'Dinheiro'), ('3', 'Débito'), ('4', 'Crédito')], default='1', help_text='Tipo de pagamento', max_length=1, verbose_name='Tipo')),
                ('valor_original', models.DecimalField(decimal_places=2, help_text='Valor original da venda', max_digits=10, verbose_name='Valor Original')),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final')),
                ('parcelas', models.PositiveIntegerField(default=1, help_text='Número de parcelas', verbose_name='Número de Parcelas')),
                ('data_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Pagamento')),
                ('estadia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='estadias.estadia', verbose_name='Estadia')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
