# Generated by Django 5.2.6 on 2025-11-04 01:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='parcelas',
            field=models.IntegerField(choices=[(Decimal('0.00'), 1), (Decimal('2.50'), 2), (Decimal('3.00'), 3), (Decimal('3.50'), 4), (Decimal('4.00'), 5), (Decimal('8.50'), 6), (Decimal('9.00'), 7), (Decimal('9.50'), 8), (Decimal('10.00'), 9), (Decimal('10.50'), 10), (Decimal('11.00'), 11), (Decimal('12.50'), 12)], default=1, verbose_name='Parcelas'),
        ),
    ]
