# Generated by Django 5.2.6 on 2025-11-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_pagamento_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='parcelas',
            field=models.IntegerField(choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=1, verbose_name='Parcelas'),
        ),
    ]
