# Generated by Django 5.2.6 on 2025-10-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_pessoajuridica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Numero da Placa', max_length=7, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('1', 'Carro'), ('2', 'Moto'), ('3', 'Caminhoneta')], default='1', help_text='Classe do carro', max_length=1, verbose_name='Tipo')),
                ('marca', models.CharField(help_text='Marca do veiculo', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo do veiculo', max_length=50, verbose_name='Modelo')),
                ('ano', models.CharField(help_text='Ano do veiculo', max_length=4, verbose_name='Ano')),
                ('cliente_fisico', models.ForeignKey(blank=True, help_text='Nome do Cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.pessoafisica', verbose_name='Cliente')),
                ('cliente_juridico', models.ForeignKey(blank=True, help_text='Nome do Jurídica', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.pessoajuridica', verbose_name='Cliente jurídico')),
            ],
        ),
    ]
