# Generated by Django 5.2.6 on 2025-10-16 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Numero da Placa', max_length=7, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('1', 'Carro'), ('2', 'Moto'), ('3', 'Caminhonete')], default='1', help_text='Classe do carro', max_length=1, verbose_name='Tipo')),
                ('marca', models.CharField(help_text='Marca do veiculo', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo do veiculo', max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(help_text='Ano do veiculo', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('pessoas_autorizadas', models.ManyToManyField(blank=True, null=True, related_name='autorizadas', to='clientes.pessoafisica', verbose_name='Pessoas autorizadas')),
                ('proprietario', models.ForeignKey(help_text='Nome do Proprietário', on_delete=django.db.models.deletion.CASCADE, to='clientes.pessoa', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
