# Generated by Django 5.2.6 on 2025-10-08 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculos',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='ano',
            field=models.IntegerField(help_text='Ano do veiculo', max_length=4, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Carro'), ('2', 'Moto'), ('3', 'Caminhonete')], default='1', help_text='Classe do carro', max_length=1, verbose_name='Tipo'),
        ),
    ]
