# Generated by Django 5.2.6 on 2025-10-08 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculos_options_alter_veiculos_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='ano',
            field=models.IntegerField(help_text='Ano do veiculo', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano'),
        ),
    ]
