# Generated by Django 5.2.6 on 2025-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Número do Telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='endereço de E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('cnpj', models.CharField(help_text='CNPJ Completo', max_length=15, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
