# Generated by Django 5.2.6 on 2025-10-16 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_da_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor total')),
                ('tipo', models.CharField(choices=[('1', 'Carro'), ('2', 'Moto'), ('3', 'Caminhonete')], default='1', help_text='Classe do carro', max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor total')),
                ('funcionario_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='func_entrada', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('funcionario_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='func_saida', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculos')),
            ],
            options={
                'verbose_name': 'Estadia',
                'verbose_name_plural': 'Estadias',
                'ordering': ['entrada'],
            },
        ),
    ]
