# Generated by Django 5.2.6 on 2025-10-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='funcionario_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='func_entrada', to='funcionarios.funcionario', verbose_name='Funcionário Entrada'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='funcionario_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='func_saida', to='funcionarios.funcionario', verbose_name='Funcionário Saida'),
        ),
    ]
