# Generated by Django 5.2.6 on 2025-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0002_alter_estadia_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='situacao',
            field=models.CharField(choices=[('1', 'Estacionado'), ('2', 'Pago')], default='1', max_length=1),
        ),
    ]
