# Generated by Django 5.2.6 on 2025-11-05 20:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0003_estadia_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadia',
            options={'ordering': ['-entrada'], 'verbose_name': 'Estadia', 'verbose_name_plural': 'Estadias'},
        ),
        migrations.AlterModelOptions(
            name='valorhora',
            options={'verbose_name': 'Valor por Hora', 'verbose_name_plural': 'Valores por Hora'},
        ),
        migrations.AlterField(
            model_name='valorhora',
            name='valor_da_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor total'),
        ),
    ]
