# Generated by Django 5.2.6 on 2025-11-05 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0004_alter_estadia_options_alter_valorhora_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorhora',
            name='valor_da_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor total'),
        ),
    ]
