# Generated by Django 5.2.6 on 2025-11-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0005_alter_valorhora_valor_da_hora'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculos', verbose_name='Proprietário/Veiculo '),
        ),
    ]
