# Generated by Django 5.2 on 2025-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0006_alter_estadia_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='valor_tipo_veiculo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor por hora aplicado'),
        ),
    ]
